#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doancosonganh
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANLYQUANAN")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_LOAISANPHAM(TBL_LOAISANPHAM instance);
    partial void UpdateTBL_LOAISANPHAM(TBL_LOAISANPHAM instance);
    partial void DeleteTBL_LOAISANPHAM(TBL_LOAISANPHAM instance);
    partial void InsertTBL_BAN(TBL_BAN instance);
    partial void UpdateTBL_BAN(TBL_BAN instance);
    partial void DeleteTBL_BAN(TBL_BAN instance);
    partial void InsertTBL_HOADON(TBL_HOADON instance);
    partial void UpdateTBL_HOADON(TBL_HOADON instance);
    partial void DeleteTBL_HOADON(TBL_HOADON instance);
    partial void InsertTBL_HOADONCT(TBL_HOADONCT instance);
    partial void UpdateTBL_HOADONCT(TBL_HOADONCT instance);
    partial void DeleteTBL_HOADONCT(TBL_HOADONCT instance);
    partial void InsertTBL_SANPHAM(TBL_SANPHAM instance);
    partial void UpdateTBL_SANPHAM(TBL_SANPHAM instance);
    partial void DeleteTBL_SANPHAM(TBL_SANPHAM instance);
    partial void InsertTBL_NHANVIEN(TBL_NHANVIEN instance);
    partial void UpdateTBL_NHANVIEN(TBL_NHANVIEN instance);
    partial void DeleteTBL_NHANVIEN(TBL_NHANVIEN instance);
    partial void InsertTBL_TINHLUONG_1(TBL_TINHLUONG_1 instance);
    partial void UpdateTBL_TINHLUONG_1(TBL_TINHLUONG_1 instance);
    partial void DeleteTBL_TINHLUONG_1(TBL_TINHLUONG_1 instance);
    partial void InsertTBL_QUANLYTAIKHOAN(TBL_QUANLYTAIKHOAN instance);
    partial void UpdateTBL_QUANLYTAIKHOAN(TBL_QUANLYTAIKHOAN instance);
    partial void DeleteTBL_QUANLYTAIKHOAN(TBL_QUANLYTAIKHOAN instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::doancosonganh.Properties.Settings.Default.QUANLYQUANANConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_LOAISANPHAM> TBL_LOAISANPHAMs
		{
			get
			{
				return this.GetTable<TBL_LOAISANPHAM>();
			}
		}
		
		public System.Data.Linq.Table<TBL_BAN> TBL_BANs
		{
			get
			{
				return this.GetTable<TBL_BAN>();
			}
		}
		
		public System.Data.Linq.Table<TBL_HOADON> TBL_HOADONs
		{
			get
			{
				return this.GetTable<TBL_HOADON>();
			}
		}
		
		public System.Data.Linq.Table<TBL_HOADONCT> TBL_HOADONCTs
		{
			get
			{
				return this.GetTable<TBL_HOADONCT>();
			}
		}
		
		public System.Data.Linq.Table<TBL_SANPHAM> TBL_SANPHAMs
		{
			get
			{
				return this.GetTable<TBL_SANPHAM>();
			}
		}
		
		public System.Data.Linq.Table<TBL_NHANVIEN> TBL_NHANVIENs
		{
			get
			{
				return this.GetTable<TBL_NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<TBL_TINHLUONG_1> TBL_TINHLUONG_1s
		{
			get
			{
				return this.GetTable<TBL_TINHLUONG_1>();
			}
		}
		
		public System.Data.Linq.Table<TBL_QUANLYTAIKHOAN> TBL_QUANLYTAIKHOANs
		{
			get
			{
				return this.GetTable<TBL_QUANLYTAIKHOAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_LOAISANPHAM")]
	public partial class TBL_LOAISANPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MASANPHAM;
		
		private string _LOAISANPHAM;
		
		private string _TENSANPHAM;
		
		private System.Nullable<int> _SOLUONG;
		
		private System.Nullable<double> _DONGIA;
		
		private System.Data.Linq.Binary _HINH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMASANPHAMChanging(string value);
    partial void OnMASANPHAMChanged();
    partial void OnLOAISANPHAMChanging(string value);
    partial void OnLOAISANPHAMChanged();
    partial void OnTENSANPHAMChanging(string value);
    partial void OnTENSANPHAMChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnDONGIAChanging(System.Nullable<double> value);
    partial void OnDONGIAChanged();
    partial void OnHINHChanging(System.Data.Linq.Binary value);
    partial void OnHINHChanged();
    #endregion
		
		public TBL_LOAISANPHAM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASANPHAM", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASANPHAM
		{
			get
			{
				return this._MASANPHAM;
			}
			set
			{
				if ((this._MASANPHAM != value))
				{
					this.OnMASANPHAMChanging(value);
					this.SendPropertyChanging();
					this._MASANPHAM = value;
					this.SendPropertyChanged("MASANPHAM");
					this.OnMASANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAISANPHAM", DbType="NVarChar(50)")]
		public string LOAISANPHAM
		{
			get
			{
				return this._LOAISANPHAM;
			}
			set
			{
				if ((this._LOAISANPHAM != value))
				{
					this.OnLOAISANPHAMChanging(value);
					this.SendPropertyChanging();
					this._LOAISANPHAM = value;
					this.SendPropertyChanged("LOAISANPHAM");
					this.OnLOAISANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSANPHAM", DbType="NVarChar(50)")]
		public string TENSANPHAM
		{
			get
			{
				return this._TENSANPHAM;
			}
			set
			{
				if ((this._TENSANPHAM != value))
				{
					this.OnTENSANPHAMChanging(value);
					this.SendPropertyChanging();
					this._TENSANPHAM = value;
					this.SendPropertyChanged("TENSANPHAM");
					this.OnTENSANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIA", DbType="Float")]
		public System.Nullable<double> DONGIA
		{
			get
			{
				return this._DONGIA;
			}
			set
			{
				if ((this._DONGIA != value))
				{
					this.OnDONGIAChanging(value);
					this.SendPropertyChanging();
					this._DONGIA = value;
					this.SendPropertyChanged("DONGIA");
					this.OnDONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HINH
		{
			get
			{
				return this._HINH;
			}
			set
			{
				if ((this._HINH != value))
				{
					this.OnHINHChanging(value);
					this.SendPropertyChanging();
					this._HINH = value;
					this.SendPropertyChanged("HINH");
					this.OnHINHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_BAN")]
	public partial class TBL_BAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MASOBAN;
		
		private System.Nullable<int> _SOBAN;
		
		private string _TRANGTHAI;
		
		private System.Nullable<int> _SONGUOI;
		
		private string _TENKHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMASOBANChanging(string value);
    partial void OnMASOBANChanged();
    partial void OnSOBANChanging(System.Nullable<int> value);
    partial void OnSOBANChanged();
    partial void OnTRANGTHAIChanging(string value);
    partial void OnTRANGTHAIChanged();
    partial void OnSONGUOIChanging(System.Nullable<int> value);
    partial void OnSONGUOIChanged();
    partial void OnTENKHACHHANGChanging(string value);
    partial void OnTENKHACHHANGChanged();
    #endregion
		
		public TBL_BAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASOBAN", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASOBAN
		{
			get
			{
				return this._MASOBAN;
			}
			set
			{
				if ((this._MASOBAN != value))
				{
					this.OnMASOBANChanging(value);
					this.SendPropertyChanging();
					this._MASOBAN = value;
					this.SendPropertyChanged("MASOBAN");
					this.OnMASOBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOBAN", DbType="Int")]
		public System.Nullable<int> SOBAN
		{
			get
			{
				return this._SOBAN;
			}
			set
			{
				if ((this._SOBAN != value))
				{
					this.OnSOBANChanging(value);
					this.SendPropertyChanging();
					this._SOBAN = value;
					this.SendPropertyChanged("SOBAN");
					this.OnSOBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="NVarChar(50)")]
		public string TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONGUOI", DbType="Int")]
		public System.Nullable<int> SONGUOI
		{
			get
			{
				return this._SONGUOI;
			}
			set
			{
				if ((this._SONGUOI != value))
				{
					this.OnSONGUOIChanging(value);
					this.SendPropertyChanging();
					this._SONGUOI = value;
					this.SendPropertyChanged("SONGUOI");
					this.OnSONGUOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKHACHHANG", DbType="NVarChar(MAX)")]
		public string TENKHACHHANG
		{
			get
			{
				return this._TENKHACHHANG;
			}
			set
			{
				if ((this._TENKHACHHANG != value))
				{
					this.OnTENKHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._TENKHACHHANG = value;
					this.SendPropertyChanged("TENKHACHHANG");
					this.OnTENKHACHHANGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_HOADON")]
	public partial class TBL_HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHDBAN;
		
		private string _MANV;
		
		private System.Nullable<System.DateTime> _NGAYBAN;
		
		private string _MAKHACH;
		
		private System.Nullable<double> _TONGTIEN;
		
		private System.Nullable<bool> _THANHTOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDBANChanging(string value);
    partial void OnMAHDBANChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnNGAYBANChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYBANChanged();
    partial void OnMAKHACHChanging(string value);
    partial void OnMAKHACHChanged();
    partial void OnTONGTIENChanging(System.Nullable<double> value);
    partial void OnTONGTIENChanged();
    partial void OnTHANHTOANChanging(System.Nullable<bool> value);
    partial void OnTHANHTOANChanged();
    #endregion
		
		public TBL_HOADON()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHDBAN", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHDBAN
		{
			get
			{
				return this._MAHDBAN;
			}
			set
			{
				if ((this._MAHDBAN != value))
				{
					this.OnMAHDBANChanging(value);
					this.SendPropertyChanging();
					this._MAHDBAN = value;
					this.SendPropertyChanged("MAHDBAN");
					this.OnMAHDBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(5)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYBAN", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYBAN
		{
			get
			{
				return this._NGAYBAN;
			}
			set
			{
				if ((this._NGAYBAN != value))
				{
					this.OnNGAYBANChanging(value);
					this.SendPropertyChanging();
					this._NGAYBAN = value;
					this.SendPropertyChanged("NGAYBAN");
					this.OnNGAYBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKHACH", DbType="VarChar(10)")]
		public string MAKHACH
		{
			get
			{
				return this._MAKHACH;
			}
			set
			{
				if ((this._MAKHACH != value))
				{
					this.OnMAKHACHChanging(value);
					this.SendPropertyChanging();
					this._MAKHACH = value;
					this.SendPropertyChanged("MAKHACH");
					this.OnMAKHACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Float")]
		public System.Nullable<double> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTOAN", DbType="Bit")]
		public System.Nullable<bool> THANHTOAN
		{
			get
			{
				return this._THANHTOAN;
			}
			set
			{
				if ((this._THANHTOAN != value))
				{
					this.OnTHANHTOANChanging(value);
					this.SendPropertyChanging();
					this._THANHTOAN = value;
					this.SendPropertyChanged("THANHTOAN");
					this.OnTHANHTOANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_HOADONCT")]
	public partial class TBL_HOADONCT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private string _MAHDBAN;
		
		private string _MASAPHAM;
		
		private string _TENSANPHAM;
		
		private System.Nullable<int> _SOLUONG;
		
		private System.Nullable<double> _GIA;
		
		private System.Nullable<int> _SOBAN;
		
		private System.Nullable<bool> _THANHTOAN;
		
		private System.Nullable<int> _PHANBIET;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnMAHDBANChanging(string value);
    partial void OnMAHDBANChanged();
    partial void OnMASAPHAMChanging(string value);
    partial void OnMASAPHAMChanged();
    partial void OnTENSANPHAMChanging(string value);
    partial void OnTENSANPHAMChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnGIAChanging(System.Nullable<double> value);
    partial void OnGIAChanged();
    partial void OnSOBANChanging(System.Nullable<int> value);
    partial void OnSOBANChanged();
    partial void OnTHANHTOANChanging(System.Nullable<bool> value);
    partial void OnTHANHTOANChanged();
    partial void OnPHANBIETChanging(System.Nullable<int> value);
    partial void OnPHANBIETChanged();
    #endregion
		
		public TBL_HOADONCT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHDBAN", DbType="NChar(5)")]
		public string MAHDBAN
		{
			get
			{
				return this._MAHDBAN;
			}
			set
			{
				if ((this._MAHDBAN != value))
				{
					this.OnMAHDBANChanging(value);
					this.SendPropertyChanging();
					this._MAHDBAN = value;
					this.SendPropertyChanged("MAHDBAN");
					this.OnMAHDBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASAPHAM", DbType="NChar(5)")]
		public string MASAPHAM
		{
			get
			{
				return this._MASAPHAM;
			}
			set
			{
				if ((this._MASAPHAM != value))
				{
					this.OnMASAPHAMChanging(value);
					this.SendPropertyChanging();
					this._MASAPHAM = value;
					this.SendPropertyChanged("MASAPHAM");
					this.OnMASAPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSANPHAM", DbType="NVarChar(50)")]
		public string TENSANPHAM
		{
			get
			{
				return this._TENSANPHAM;
			}
			set
			{
				if ((this._TENSANPHAM != value))
				{
					this.OnTENSANPHAMChanging(value);
					this.SendPropertyChanging();
					this._TENSANPHAM = value;
					this.SendPropertyChanged("TENSANPHAM");
					this.OnTENSANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA", DbType="Float")]
		public System.Nullable<double> GIA
		{
			get
			{
				return this._GIA;
			}
			set
			{
				if ((this._GIA != value))
				{
					this.OnGIAChanging(value);
					this.SendPropertyChanging();
					this._GIA = value;
					this.SendPropertyChanged("GIA");
					this.OnGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOBAN", DbType="Int")]
		public System.Nullable<int> SOBAN
		{
			get
			{
				return this._SOBAN;
			}
			set
			{
				if ((this._SOBAN != value))
				{
					this.OnSOBANChanging(value);
					this.SendPropertyChanging();
					this._SOBAN = value;
					this.SendPropertyChanged("SOBAN");
					this.OnSOBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHTOAN", DbType="Bit")]
		public System.Nullable<bool> THANHTOAN
		{
			get
			{
				return this._THANHTOAN;
			}
			set
			{
				if ((this._THANHTOAN != value))
				{
					this.OnTHANHTOANChanging(value);
					this.SendPropertyChanging();
					this._THANHTOAN = value;
					this.SendPropertyChanged("THANHTOAN");
					this.OnTHANHTOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHANBIET", DbType="Int")]
		public System.Nullable<int> PHANBIET
		{
			get
			{
				return this._PHANBIET;
			}
			set
			{
				if ((this._PHANBIET != value))
				{
					this.OnPHANBIETChanging(value);
					this.SendPropertyChanging();
					this._PHANBIET = value;
					this.SendPropertyChanged("PHANBIET");
					this.OnPHANBIETChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_SANPHAM")]
	public partial class TBL_SANPHAM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MASANPHAM;
		
		private string _TENSANPHAM;
		
		private string _LOAISANPHAM;
		
		private System.Nullable<int> _SOLUONG;
		
		private System.Nullable<double> _GIA;
		
		private System.Nullable<System.DateTime> _THOIGIAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMASANPHAMChanging(string value);
    partial void OnMASANPHAMChanged();
    partial void OnTENSANPHAMChanging(string value);
    partial void OnTENSANPHAMChanged();
    partial void OnLOAISANPHAMChanging(string value);
    partial void OnLOAISANPHAMChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnGIAChanging(System.Nullable<double> value);
    partial void OnGIAChanged();
    partial void OnTHOIGIANChanging(System.Nullable<System.DateTime> value);
    partial void OnTHOIGIANChanged();
    #endregion
		
		public TBL_SANPHAM()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASANPHAM", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASANPHAM
		{
			get
			{
				return this._MASANPHAM;
			}
			set
			{
				if ((this._MASANPHAM != value))
				{
					this.OnMASANPHAMChanging(value);
					this.SendPropertyChanging();
					this._MASANPHAM = value;
					this.SendPropertyChanged("MASANPHAM");
					this.OnMASANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSANPHAM", DbType="NVarChar(50)")]
		public string TENSANPHAM
		{
			get
			{
				return this._TENSANPHAM;
			}
			set
			{
				if ((this._TENSANPHAM != value))
				{
					this.OnTENSANPHAMChanging(value);
					this.SendPropertyChanging();
					this._TENSANPHAM = value;
					this.SendPropertyChanged("TENSANPHAM");
					this.OnTENSANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAISANPHAM", DbType="NVarChar(50)")]
		public string LOAISANPHAM
		{
			get
			{
				return this._LOAISANPHAM;
			}
			set
			{
				if ((this._LOAISANPHAM != value))
				{
					this.OnLOAISANPHAMChanging(value);
					this.SendPropertyChanging();
					this._LOAISANPHAM = value;
					this.SendPropertyChanged("LOAISANPHAM");
					this.OnLOAISANPHAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA", DbType="Float")]
		public System.Nullable<double> GIA
		{
			get
			{
				return this._GIA;
			}
			set
			{
				if ((this._GIA != value))
				{
					this.OnGIAChanging(value);
					this.SendPropertyChanging();
					this._GIA = value;
					this.SendPropertyChanged("GIA");
					this.OnGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIAN", DbType="DateTime")]
		public System.Nullable<System.DateTime> THOIGIAN
		{
			get
			{
				return this._THOIGIAN;
			}
			set
			{
				if ((this._THOIGIAN != value))
				{
					this.OnTHOIGIANChanging(value);
					this.SendPropertyChanging();
					this._THOIGIAN = value;
					this.SendPropertyChanged("THOIGIAN");
					this.OnTHOIGIANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_NHANVIEN")]
	public partial class TBL_NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _TENNHANVIEN;
		
		private string _GIOITINH;
		
		private System.Nullable<double> _LUONG;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _CHUCVU;
		
		private string _DIACHI;
		
		private System.Data.Linq.Binary _HINH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnTENNHANVIENChanging(string value);
    partial void OnTENNHANVIENChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnLUONGChanging(System.Nullable<double> value);
    partial void OnLUONGChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnCHUCVUChanging(string value);
    partial void OnCHUCVUChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnHINHChanging(System.Data.Linq.Binary value);
    partial void OnHINHChanged();
    #endregion
		
		public TBL_NHANVIEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNHANVIEN", DbType="NVarChar(50)")]
		public string TENNHANVIEN
		{
			get
			{
				return this._TENNHANVIEN;
			}
			set
			{
				if ((this._TENNHANVIEN != value))
				{
					this.OnTENNHANVIENChanging(value);
					this.SendPropertyChanging();
					this._TENNHANVIEN = value;
					this.SendPropertyChanged("TENNHANVIEN");
					this.OnTENNHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(5)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUONG", DbType="Float")]
		public System.Nullable<double> LUONG
		{
			get
			{
				return this._LUONG;
			}
			set
			{
				if ((this._LUONG != value))
				{
					this.OnLUONGChanging(value);
					this.SendPropertyChanging();
					this._LUONG = value;
					this.SendPropertyChanged("LUONG");
					this.OnLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="NVarChar(50)")]
		public string CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					this.OnCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._CHUCVU = value;
					this.SendPropertyChanged("CHUCVU");
					this.OnCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(MAX)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary HINH
		{
			get
			{
				return this._HINH;
			}
			set
			{
				if ((this._HINH != value))
				{
					this.OnHINHChanging(value);
					this.SendPropertyChanging();
					this._HINH = value;
					this.SendPropertyChanged("HINH");
					this.OnHINHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_TINHLUONG_1")]
	public partial class TBL_TINHLUONG_1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _CHUCVU;
		
		private System.Nullable<int> _LUONG;
		
		private System.Nullable<System.DateTime> _NGAYNHAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnCHUCVUChanging(string value);
    partial void OnCHUCVUChanged();
    partial void OnLUONGChanging(System.Nullable<int> value);
    partial void OnLUONGChanged();
    partial void OnNGAYNHANChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYNHANChanged();
    #endregion
		
		public TBL_TINHLUONG_1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="NChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="NVarChar(50)")]
		public string CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					this.OnCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._CHUCVU = value;
					this.SendPropertyChanged("CHUCVU");
					this.OnCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUONG", DbType="Int")]
		public System.Nullable<int> LUONG
		{
			get
			{
				return this._LUONG;
			}
			set
			{
				if ((this._LUONG != value))
				{
					this.OnLUONGChanging(value);
					this.SendPropertyChanging();
					this._LUONG = value;
					this.SendPropertyChanged("LUONG");
					this.OnLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYNHAN", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAYNHAN
		{
			get
			{
				return this._NGAYNHAN;
			}
			set
			{
				if ((this._NGAYNHAN != value))
				{
					this.OnNGAYNHANChanging(value);
					this.SendPropertyChanging();
					this._NGAYNHAN = value;
					this.SendPropertyChanged("NGAYNHAN");
					this.OnNGAYNHANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_QUANLYTAIKHOAN")]
	public partial class TBL_QUANLYTAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATAIKHOAN;
		
		private string _TENTAIKHOAN;
		
		private string _MATKHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATAIKHOANChanging(string value);
    partial void OnMATAIKHOANChanged();
    partial void OnTENTAIKHOANChanging(string value);
    partial void OnTENTAIKHOANChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    #endregion
		
		public TBL_QUANLYTAIKHOAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATAIKHOAN", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATAIKHOAN
		{
			get
			{
				return this._MATAIKHOAN;
			}
			set
			{
				if ((this._MATAIKHOAN != value))
				{
					this.OnMATAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._MATAIKHOAN = value;
					this.SendPropertyChanged("MATAIKHOAN");
					this.OnMATAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTAIKHOAN", DbType="NVarChar(20)")]
		public string TENTAIKHOAN
		{
			get
			{
				return this._TENTAIKHOAN;
			}
			set
			{
				if ((this._TENTAIKHOAN != value))
				{
					this.OnTENTAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._TENTAIKHOAN = value;
					this.SendPropertyChanged("TENTAIKHOAN");
					this.OnTENTAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="NVarChar(20)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
